FROM nginx:1.17.2-alpine

## Security and Configurations
# Extra files
RUN rm /etc/nginx/conf.d/default.conf
RUN set -x ; \
    addgroup -g 82 -S www-data ; \
    adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

# Load Site Configuration
RUN mkdir -p /etc/nginx/sites-enabled/
RUN mkdir -p /var/www/site/static/

COPY proxy_params /etc/nginx/
COPY nginx.conf /etc/nginx/

## Load Static and errors
COPY collectstatic /var/www/site/static

# Finish
RUN chown -R www-data:www-data /var/www/site