# Generated by Django 3.0 on 2020-04-11 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Graveyard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=5)),
                ('actualTurn', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Deck')),
                ('graveyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Graveyard')),
                ('player_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.Player')),
                ('player_guest_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_field', to='game.PlayerField')),
                ('player_guest_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_hand', to='game.Hand')),
                ('player_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.Player')),
                ('player_owner_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_field', to='game.PlayerField')),
                ('player_owner_hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_hand', to='game.Hand')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('suit', models.IntegerField(choices=[(0, 'Trebol'), (1, 'Corazon'), (2, 'Espada'), (3, 'Diamante'), (99, 'Joker')])),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Deck')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.PlayerField')),
                ('graveyard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Graveyard')),
                ('hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Hand')),
            ],
        ),
    ]
