# Generated by Django 3.0 on 2020-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='graveyard_position',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='graveyard',
            name='top_card_position',
            field=models.IntegerField(default=-1),
        ),
    ]
