# Generated by Django 3.0 on 2020-04-11 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20200411_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='actualTurn',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
