# Generated by Django 3.0 on 2020-04-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200411_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=12),
        ),
    ]
